server:
  port: 8090
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nxx?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Gxy123

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:mapping/*.xml
