server:
  port: 8090
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nxx?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB



mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:mapping/*.xml
